version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hive-app-backend
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - hive-net

  redis:
    image: redis:7-alpine
    container_name: hive-app-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - hive-net

networks:
  hive-net:
    driver: bridge
